---
- hosts: all
  become: yes

  roles:
  - role: ../roles/gather-desktop-environment-facts
  - role: ../roles/ubuntu-pre
  - role: ../roles/crownlabs
    when: crownlabs_mode
  - role: ../roles/firefox    
  - role: ../roles/ubuntu-post
